#!/bin/sh

for file in $(find chrome/app/theme -name product_logo_[0-9]*.png -a ! -name *mono* | grep -v 200); do
     size=$(basename $file | cut -d_ -f3 | sed s/\.png//)
     dest=debian/org.mojo.browser/opt/apps/org.mojo.browser/entries/icons/hicolor/$size\x$size/apps
     mkdir -p $dest
     cp $file $dest/org.mojo.browser.png
     echo copied: $file to $dest/org.mojo.borser.png
     done
